# Generated by Django 5.2 on 2025-05-25 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='station',
            fields=[
                ('ID_Station', models.AutoField(primary_key=True, serialize=False)),
                ('adresse', models.CharField(max_length=255, unique=True)),
                ('puissance', models.FloatField(blank=True, null=True)),
                ('prix_kw', models.FloatField()),
                ('disponibilite', models.BooleanField(default=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('nom', models.CharField(default='Station de recharge', max_length=100)),
                ('connector_types', models.CharField(blank=True, max_length=255, null=True)),
                ('operator', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('ID_Reservation', models.AutoField(primary_key=True, serialize=False)),
                ('time_start', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('time_end', models.DateTimeField()),
                ('power', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.proprietaireve')),
                ('ID_Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stations_photos/')),
                ('ID_Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='avi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('note', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.proprietaireve')),
                ('ID_Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='stations.station')),
            ],
        ),
    ]
